Description: >
    Creates a Bastion instance

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  AppEnvironment:
    Type: String
    Description: Environment type.

  AppCountry:
    Type: String
    Description: Country.

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Applicaion Load Balancer should be deployed to

  SubnetBastion:
    Description: Choose which private subnets the Application should be deployed to
    Type: AWS::EC2::Subnet::Id

  bastionInstanceType:
    Type: String
    Description: Instance type
    Default: t2.micro

  BastionSecurityGroup:
    Description: Select the Security Group to apply to the Application
    Type: AWS::EC2::SecurityGroup::Id

  HostKeyPair:
    Description: Select the Security Group to apply to the Application
    Type: AWS::EC2::KeyPair::KeyName
    
Mappings:

  RegionAMI:
    us-east-1:
      AmazonLinux: ami-8c1be5f6
    us-east-2:
      AmazonLinux: ami-c5062ba0
    us-west-1:
      AmazonLinux: ami-02eada62
    us-west-2:
      AmazonLinux: ami-e689729e
    sa-east-1:
      AmazonLinux: ami-f1344b9d

Resources:

  bastionHostEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref bastionInstance

  bastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref HostKeyPair
      ImageId: !FindInMap [ RegionAMI, !Ref "AWS::Region", AmazonLinux ]
      InstanceType: !Ref bastionInstanceType
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      SubnetId: !Ref SubnetBastion
      Tags:
        - Key: Name
          Value: !Sub ${AppCountry}-${AppEnvironment}-Bastion-${EnvironmentName}
        - Key: Country
          Value: !Ref AppCountry
        - Key: EnvType
          Value: !Ref AppEnvironment
      UserData:
        "Fn::Base64": !Sub |
            #!/bin/bash -ex
            yum update -y
            yum install java-1.8.0 -y
            yum remove java-1.7.0-openjdk -y
      
Outputs:

  bastionHostEIP:
    Description: Bastion IP
    Value: !Ref bastionHostEIP
